[package]
name = "Rust-Links-Extract"
version = "0.1.0"
edition = "2024"

[dependencies]
error-chain = "0.12.4"
reqwest = "0.12.23"
select = "0.6.1"
tokio = { version = "1.21.1", features = ["full"] }